# Generated by Django 2.0.5 on 2018-05-29 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('F', 'female'), ('M', 'male')], default='M', max_length=2),
        ),
    ]
