# Generated by Django 2.0.5 on 2018-05-29 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_auto_20180529_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(default='images/1.png', max_length=20),
        ),
    ]
